extends MenuButton

var popup

func _ready():
    popup = get_popup()
    popup.add_item("Genesis.txt")
    popup.add_item("Exodus.txt")
    popup.add_item("Leviticus.txt")
    popup.add_item("Numbers.txt")
    popup.add_item("Deuteronomy.txt")
    popup.add_item("Joshua.txt")
    popup.add_item("Judges.txt")
    popup.add_item("Ruth.txt")
    popup.add_item("1 Samuel.txt")
    popup.add_item("2 Samuel.txt")
    popup.add_item("1 Kings.txt")
    popup.add_item("2 Kings.txt")
    popup.add_item("1 Chronicles.txt")
    popup.add_item("2 Chronicles.txt")
    popup.add_item("Ezra.txt")
    popup.add_item("Nehemiah.txt")
    popup.add_item("Esther.txt")
    popup.add_item("Job.txt")
    popup.add_item("Psalms.txt")
    popup.add_item("Proverbs.txt")
    popup.add_item("Ecclesiastes.txt")
    popup.add_item("SongofSolomon.txt")
    popup.add_item("Isaiah.txt")
    popup.add_item("Jeremiah.txt")
    popup.add_item("Lamentations.txt")
    popup.add_item("Ezekiel.txt")
    popup.add_item("Daniel.txt")
    popup.add_item("Hosea.txt")
    popup.add_item("Joel.txt")
    popup.add_item("Amos.txt")
    popup.add_item("Obadiah.txt")
    popup.add_item("Jonah.txt")
    popup.add_item("Micah.txt")
    popup.add_item("Nahum.txt")
    popup.add_item("Habakkuk.txt")
    popup.add_item("Zephaniah.txt")
    popup.add_item("Haggai.txt")
    popup.add_item("Zechariah.txt")
    popup.add_item("Malachi.txt")
    popup.connect("id_pressed", self, "_on_item_pressed")


func _on_item_pressed(ID):
    print(popup.get_item_text(ID), " pressed")
    var edit = get_node("/root/Node2D/TextEdit")
    var file = File.new()
    file.open("res://" +popup.get_item_text(ID), File.READ)
    var result = {}
    var f = File.new()
    f.open("res://" +popup.get_item_text(ID), File.READ)
    var index = 1
    edit.set_text(f.get_as_text())  
  #  edit.set_wrap(true)
    f.close()    
